package ar.edu.utn.frba.dds.simeal.models.repositories;

public enum TipoRepo {
  COLABORACION,
  OFERTA,
  CANJE,
  HELADERA,
  MODELO_HELADERA,
  VISITA_TECNICA,
  ESTADO_HELADERA,
  INCIDENTE,
  SUSCRIPCION,
  TARJETA_PERSONA_VULNERABLE,
  TECNICO,
  VIANDA,
  OPERACION_HELADERA,
  SOLICITUD_OPERACION_HELADERA,
  COLABORADOR,
  PERSONA_VULNERABLE,
  SENSOR, FALLA_TECNICA, ALERTA, TARJETA_COLABORADOR
}
