package ar.edu.utn.frba.dds.simeal.models.repositories;

public enum TipoRepo {
  ADHERIR_HELADERA,
  DONACION_VIANDA,
  DONACION_DINERO,
  DISTRIBUCION_VIANDA,
  DAR_DE_ALTA_PERSONA_VULNERABLE,
  OFERTA,
  CANJE,
  HELADERA,
  MODELO_HELADERA,
  VISITA_TECNICA,
  ESTADO_HELADERA,
  INCIDENTE,
  SUSCRIPCION,
  TARJETA_PERSONA_VULNERABLE,
  TECNICO,
  VIANDA,
  OPERACION_HELADERA,
  SOLICITUD_OPERACION_HELADERA,
  COLABORADOR,
  PERSONA_VULNERABLE,
  TARJETA_COLABORADOR
}
